
skillMetadata:
  sections:
    - name: Todoist Information
      fields:
        - type: label
          label: Your Todist API token can be found under your profile > Settings > Integrations (at bottom of page)
        - name: api_key
          type: password
          label: Todoist API Key
          value: ""
